todo:
  users:
    meta:
      ids: [182409893, 278461832]

    user: true
    friends: true
    groups: true
    owner_posts: true

    sample:
      meta:
        groups:
          size: 10
          per-entity: true

      groups:
        group: true
        members:
          count: 10000
        other_posts: true

        sample:
          meta:
            users:
              size: 15
              
          users:
            user: true


defaults:
  generic:
    # method:     wall.get
    # overridden: owner_id
    owner_posts:
      count: 10
      filter: owner
      extended: true

    # method:     wall.get
    # overridden: owner_id
    other_posts:
      count: 10
      filter: others
      extended: true

    # new stage
    sample:
      meta:
        users:
          size: 1000
          per-entity: false
        groups:
          size: 100
          per-entity: false

  users:
    meta:
      ids: []
      chunk: 1000

    # method:   users.get
    # overridden: user_ids
    user:
      fields: [sex, verified, bdate, city, country, home_town, education, last_seen, has_photo, 
      photo_50, followers_count, activities, interests, music, movies, tv, books, games, about]

    # method:     users.getSubscriptions
    # overridden: user_id
    groups:

    # method: friends.get
    # overridden: user_id
    friends:
      order: mobile

  groups:
    meta:
      ids: []
      chunk: 1000

    # method:     groups.getById
    # overridden: group_id
    group:
      fields: [description, fixed_post, members_count, status, 
      has_photo, photo_50, activity, age_limits, city, country]

    # method:     groups.getMembers
    # overridden: offset, group_id
    members:
      count: 2000
      